'''The following program gives us the weight of the protein PKC-Beta1'''

def main():
    '''The Protein sequence PKC_BETA1'''
    pkc_beta1 = """MADPAAGPPPSEGEESTVRFARKGALRQKNVHEVKNHKFTARFFKQPTFCSHCTDFIWGFGKQGFQCQVC
    CFVVHKRCHEFVTFSCPGADKGPASDDPRSKHKFKIHTYSSPTFCDHCGSLLYGLIHQGMKCDTCMMNVH
    KRCVMNVPSLCGTDHTERRGRIYIQAHIDREVLIVVVRDAKNLVPMDPNGLSDPYVKLKLIPDPKSESKQ
    KTKTIKCSLNPEWNETFRFQLKESDKDRRLSVEIWDWDLTSRNDFMGSLSFGISELQKAGVDGWFKLLSQ
    EEGEYFNVPVPPEGSEGNEELRQKFERAKIGQGTKAPEEKTANTISKFDNNGNRDRMKLTDFNFLMVLGK
    GSFGKVMLSERKGTDELYAVKILKKDVVIQDDDVECTMVEKRVLALPGKPPFLTQLHSCFQTMDRLYFVM
    EYVNGGDLMYHIQQVGRFKEPHAVFYAAEIAIGLFFLQSKGIIYRDLKLDNVMLDSEGHIKIADFGMCKE
    NIWDGVTTKTFCGTPDYIAPEIIAYQPYGKSVDWWAFGVLLYEMLAGQAPFEGEDEDELFQSIMEHNVAY
    PKSMSKEAVAICKGLMTKHPGKRLGCGPEGERDIKEHAFFRYIDWEKLERKEIQPPYKPKARDKRDTSNF
    DKEFTRQPVELTPTDKLFIMNLDQNEFAGFSYTNPEFVINV
    """

    # removing new lines
    pkc_beta1 = pkc_beta1.replace('\r', '').replace('\n', '')

    # to calculate the length of the protein PKC- Beta1
    length_pkc = len(pkc_beta1)
    print('The length of "Protein kinase C beta type" is:', length_pkc)
    avg_wt = 110

    # to calculate the weight of PKC- Beta1
    wt_pkc = (length_pkc * avg_wt) / 1000
    print("The average weight of this protein sequence in kilodaltons is: ", wt_pkc)

if __name__ == '__main__':
    main()
